name: Smoke Test
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  smoke_test:
    runs-on: buildjet-16vcpu-ubuntu-2004
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    environment: smoke-test
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - name: Load rust cache
        uses: astriaorg/buildjet-rust-cache@v2.5.1

      - name: Install tendermint binary
        run: |
          curl -L -O "https://github.com/tendermint/tendermint/releases/download/v0.34.24/tendermint_0.34.24_linux_amd64.tar.gz"
          tar xzf tendermint_0.34.24_linux_amd64.tar.gz tendermint
          mkdir -p $HOME/bin
          cp tendermint $HOME/bin
          echo $PATH
          export PATH=$HOME/bin:$PATH
          which tendermint

      # Build CometMock from source, specifically from the v0.34.x branch.
      - name: Install golang
        uses: actions/setup-go@v4
        with:
          go-version: 'stable'

      - name: Build cometmock
        run: |
          # cometmock_branch="v0.34.x"
          # Temporarily use feature branch for Penumbra/tower-abci support.
          cometmock_branch="ph/increase-timeout"
          git clone --depth 1 --branch "$cometmock_branch"  https://github.com/informalsystems/CometMock ../cometmock
          cd ../cometmock || exit 1
          mkdir -p $HOME/bin
          go build -o $HOME/bin/cometmock ./cometmock
          export PATH=$HOME/bin:$PATH
          which cometmock

      - name: Run the smoke test suite
        run: |
          export PATH=$HOME/bin:$PATH
          ./deployments/scripts/smoke-test.sh
        env:
          TESTNET_RUNTIME: 2m
